"""empty message

<<<<<<< HEAD:migrations/versions/c860c8ff9add_.py
Revision ID: c860c8ff9add
Revises: 
Create Date: 2021-05-08 20:50:21.895666
=======
Revision ID: 6a82a582f18f
Revises: 
Create Date: 2021-05-08 21:00:16.484426
>>>>>>> 9566629f211d42abe3c784b0eff134a1fb50f2d5:migrations/versions/6a82a582f18f_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/c860c8ff9add_.py
revision = 'c860c8ff9add'
=======
revision = '6a82a582f18f'
>>>>>>> 9566629f211d42abe3c784b0eff134a1fb50f2d5:migrations/versions/6a82a582f18f_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('security_question', sa.String(length=200), nullable=False),
    sa.Column('security_answer', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('provincia', sa.String(length=30), nullable=False),
    sa.Column('dificultad', sa.String(length=30), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('total_comment', sa.Integer(), nullable=False),
    sa.Column('total_like', sa.Integer(), nullable=False),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iduser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.Column('idpost', sa.Integer(), nullable=True),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idpost'], ['post.id'], ),
    sa.ForeignKeyConstraint(['iduser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('idpost', sa.Integer(), nullable=True),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idpost'], ['post.id'], ),
    sa.ForeignKeyConstraint(['iduser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_like')
    op.drop_table('post_comments')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
